spring.application.name=enterprise-ai-platform

##################################################
# AI Configuration
##################################################

##################################################
# Chat Model
##################################################
ai.chat.provider=ollama
ai.chat.base-url=http://localhost:11434
ai.chat.model=qwen2.5:0.5b

##################################################
# Embedding Model
##################################################
ai.embedding.provider=ollama
ai.embedding.base-url=http://localhost:11434
ai.embedding.model=all-minilm

##################################################
# Chunking
##################################################
ai.chunk.max-sentences=2

##################################################
# Vector Store
##################################################
ai.vectorstore.provider=in-memory

##################################################
# PostgreSQL
##################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_ai
spring.datasource.username=enterprise_ai
spring.datasource.password=enterprise_ai
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################
# JPA
##################################################
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

##################################################
# Flyway
##################################################
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

##################################################
# Logging
##################################################
logging.level.root=INFO
logging.level.com.sam.enterpriseai=INFO
logging.level.org.flywaydb=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n