spring.application.name=enterprise-ai-platform

##########################################################
# AI Configuration
##########################################################

ai.provider=ollama
ai.chat.model=qwen2.5:0.5b

##########################################################
# Ollama Configuration
##########################################################

ai.ollama.base-url=http://localhost:11434
ai.ollama.generate-endpoint=/api/generate