spring.application.name=enterprise-ai-platform

##################################################
# AI Configuration
##################################################

##################################################
# Chat Model
##################################################
ai.chat.provider=ollama
ai.chat.base-url=http://localhost:11434
ai.chat.model=qwen2.5:0.5b

#Tested chat models
#qwen2.5:3b
# --slow as compared to - qwen2.5:0.5b - Takes approx 2 plus minutes
# --more accurate answers

#qwen2.5:0.5b
# --fast as compared to - qwen2.5:3b - Takes approx 25-30 seconds
# --hallucinates mostly

##################################################
# Embedding Model
##################################################
ai.embedding.provider=ollama
ai.embedding.base-url=http://localhost:11434
ai.embedding.model=nomic-embed-text
ai.embedding.dimension=768

#Tested embedding models
#nomic-embed-text
# --supports 768 dimensions but slow as compared to - all-minilm

#all-minilm
# --supports 384 dimensions but fast as compared to - nomic-embed-text

##################################################
# Vector Store
##################################################
##Options- in-memory,pgvector
ai.vectorstore.provider=pgvector

##################################################
# PgVector Vector Store
##################################################
ai.vectorstore.pgvector.host=localhost
ai.vectorstore.pgvector.port=5432
ai.vectorstore.pgvector.database=enterprise_ai
ai.vectorstore.pgvector.user=enterprise_ai
ai.vectorstore.pgvector.password=enterprise_ai
ai.vectorstore.pgvector.table=knowledge_vectors

##################################################
# PostgreSQL
##################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_ai
spring.datasource.username=enterprise_ai
spring.datasource.password=enterprise_ai
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################
# JPA
##################################################
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

##################################################
# Flyway
##################################################
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

##################################################
# Logging
##################################################
logging.level.root=INFO
logging.level.com.sam.enterpriseai=INFO
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.postgresql=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n